workshop_title: 
signature:              # Signature for message body (should be a name;)
mutt_account:         # path to mutt account that will be used for sending the mails
csv_file:             # filename of csv table (default: teilnehmende.csv)
filedir:              # path to pdf folder (default: teilnahmebestätigungen)