basedir:              # set basic working directory
csv_file:             # path to csv table
filedir:              # path to pdf folder
workshop_title:       
mutt_account:         # path to mutt account that will be used for sending the mails
signature:            # Signature for message body (should be a name;)

